function updateDB() {
    // Get all of the pages in the directory...
    // For each page...
    // Get the page name.
    // Get the page URL.
    // Create a row for the page...
    // Get the elements on the page.
    // For each element...
    // Get the element id.
    // Get the html for the elements.
    // Create a row for the element...
    // Get the inner text if it exists.
    // Create a row for the content...
}